### ISSUE TITLE
Can not implement auth strategy (jwt)

### ISSUE THREAD

**Issue by noluckjustskill** [marcoesposito/nestjs-typeorm-multi-tenant#2]
Hello! Thank you for your solution.

I tried to implement JWT-passport auth (https://docs.nestjs.com/techniques/authentication#implementing-passport-jwt), but it does not work: `Error: Unknown authentication strategy "jwt"`. I think it happens because tenant's module or services (in your app book.service) have `scope: Scope.REQUEST`.

How I can implement auth for tenants? 
Do I need request scoped strategy (https://docs.nestjs.com/techniques/authentication#request-scoped-strategies)?
Thanks.

**Comment by nick-lehmann** [comment]
Hi @noluckjustskill, I faced the same problem today. Yes, if you also scope the passport strategy to the request the issue will be fixed.

**Comment by noluckjustskill** [comment]
Hi @nick-lehmann, I used https://docs.nestjs.com/techniques/authentication#request-scoped-strategies and faced a problem that when using defenders request object in scoped provider is undefined: https://github.com/nestjs/nest/issues/5274

**Comment by noluckjustskill** [comment]
@nick-lehmann @marcoesposito I created custom auth-guard based on interceptor: https://github.com/noluckjustskill/nestjs-graphql-multitenants
